# Grafana unified alerting — Mattermost contact point (generated by tofu apply).
grafana:
  alerting:
    contactpoints.yaml:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: mattermost
          receivers:
            - uid: mattermost
              type: slack
              settings:
                url: ${mattermost_webhook_url}
    policies.yaml:
      apiVersion: 1
      policies:
        - orgId: 1
          receiver: mattermost
          group_by:
            - grafana_folder
            - alertname
